data:extend(
{
    -- hydrogen sulfide
    {
        type = "fluid",
        name = "fluid-hydrogen-sulfide",
        icon = "__factoricanrefinery__/graphics/icons/fluid-hydrogen-sulfide.png",
        icon_size = 32,
        subgroup = "fluids-refinery",
        default_temperature = 25,
        heat_capacity = "0.1KJ",
        base_color = {r = 0.75, g = 0.65, b = 0.1},
        flow_color = {r = 0.75, g = 0.65, b = 0.1},
        max_temperature = 100,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
    -- sulfur dioxide
    {
        type = "fluid",
        name = "fluid-sulfur-dioxide",
        icon = "__factoricanrefinery__/graphics/icons/fluid-sulfur-dioxide.png",
        icon_size = 32,
        subgroup = "fluids-refinery",
        default_temperature = 25,
        heat_capacity = "0.1KJ",
        base_color = {r = 0.75, g = 0.65, b = 0.1},
        flow_color = {r = 0.75, g = 0.65, b = 0.1},
        max_temperature = 100,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
    -- sulfur trioxide
    {
        type = "fluid",
        name = "fluid-sulfur-trioxide",
        icon = "__factoricanrefinery__/graphics/icons/fluid-sulfur-trioxide.png",
        icon_size = 32,
        subgroup = "fluids-refinery",
        default_temperature = 25,
        heat_capacity = "0.1KJ",
        base_color = {r = 0.75, g = 0.65, b = 0.1},
        flow_color = {r = 0.75, g = 0.65, b = 0.1},
        max_temperature = 100,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
    -- polymer feed
    {
        type = "fluid",
        name = "fluid-polymer-feed",
        icon = "__factoricanrefinery__/graphics/icons/fluid-polymer-feed.png",
        icon_size = 32,
        subgroup = "fluids-refinery",
        default_temperature = 25,
        heat_capacity = "0.1KJ",
        base_color = {r = 1, g = 1, b = 1},
        flow_color = {r = 1, g = 1, b = 1},
        max_temperature = 100,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
    -- crosslinker
    {
        type = "fluid",
        name = "fluid-crosslinker",
        icon = "__factoricanrefinery__/graphics/icons/fluid-crosslinker.png",
        icon_size = 32,
        subgroup = "fluids-refinery",
        default_temperature = 25,
        heat_capacity = "0.1KJ",
        base_color = {r = 1, g = 1, b = 1},
        flow_color = {r = 1, g = 1, b = 1},
        max_temperature = 100,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
    -- dead oil
    {
        type = "fluid",
        name = "fluid-dead-oil",
        icon = "__factoricanrefinery__/graphics/icons/fluid-dead-oil.png",
        icon_size = 32,
        subgroup = "fluids-refinery",
        default_temperature = 25,
        heat_capacity = "0.1KJ",
        base_color = {r = 0, g = 0, b = 0},
        flow_color = {r = 0, g = 0, b = 0},
        max_temperature = 100,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
    -- base oil
    {
        type = "fluid",
        name = "fluid-base-oil",
        icon = "__factoricanrefinery__/graphics/icons/fluid-base-oil.png",
        icon_size = 32,
        subgroup = "fluids-refinery",
        default_temperature = 25,
        heat_capacity = "0.1KJ",
        base_color = {r = 0.27, g = 0.11, b = 0},
        flow_color = {r = 0.27, g = 0.11, b = 0},
        max_temperature = 100,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
    -- fuel oil
    {
        type = "fluid",
        name = "fluid-fuel-oil",
        icon = "__factoricanrefinery__/graphics/icons/fluid-fuel-oil.png",
        icon_size = 32,
        subgroup = "fluids-refinery",
        default_temperature = 25,
        heat_capacity = "0.1KJ",
        base_color = {r = 0.86, g = 0.7, b = 0},
        flow_color = {r = 0.86, g = 0.7, b = 0},
        max_temperature = 100,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
    -- naphtha
    {
        type = "fluid",
        name = "fluid-naphtha",
        icon = "__factoricanrefinery__/graphics/icons/fluid-naphtha.png",
        icon_size = 32,
        subgroup = "fluids-refinery",
        default_temperature = 25,
        heat_capacity = "0.1KJ",
        base_color = {r = 0.65, g = 0.3, b = 0.13},
        flow_color = {r = 0.65, g = 0.3, b = 0.13},
        max_temperature = 100,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
    -- solution gas
    {
        type = "fluid",
        name = "fluid-solution-gas",
        icon = "__factoricanrefinery__/graphics/icons/fluid-solution-gas.png",
        icon_size = 32,
        subgroup = "fluids-refinery",
        default_temperature = 25,
        heat_capacity = "0.1KJ",
        base_color = {r = 0.35, g = 0.44, b = 0.29},
        flow_color = {r = 0.35, g = 0.44, b = 0.29},
        max_temperature = 100,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
    -- natural gas
    {
        type = "fluid",
        name = "fluid-natural-gas",
        icon = "__factoricanrefinery__/graphics/icons/fluid-natural-gas.png",
        icon_size = 32,
        subgroup = "fluids-refinery",
        default_temperature = 25,
        heat_capacity = "0.1KJ",
        base_color = {r = 0.35, g = 0.44, b = 0.29},
        flow_color = {r = 0.35, g = 0.44, b = 0.29},
        max_temperature = 100,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
    -- natural gas liquids
    {
        type = "fluid",
        name = "fluid-natural-gas-liquid",
        icon = "__factoricanrefinery__/graphics/icons/fluid-natural-gas-liquid.png",
        icon_size = 32,
        subgroup = "fluids-refinery",
        default_temperature = 25,
        heat_capacity = "0.1KJ",
        base_color = {r = 0.35, g = 0.44, b = 0.29},
        flow_color = {r = 0.35, g = 0.44, b = 0.29},
        max_temperature = 100,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
    -- combustion fuel
    {
        type = "fluid",
        name = "fluid-combustion-fuel",
        icon = "__factoricanrefinery__/graphics/icons/fluid-combustion-fuel.png",
        icon_size = 32,
        subgroup = "fluids-refinery",
        default_temperature = 25,
        heat_capacity = "0.1KJ",
        base_color = {r = 0.96, g = 0.44, b = 0.13},
        flow_color = {r = 0.96, g = 0.44, b = 0.13},
        max_temperature = 2000,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
})