data:extend(
{
    {
        type = "fluid",
        name = "fs-reduction-gas",
        icon = "__factoricanindustry__/graphics/icons/items/fs-reduction-gas.png",
        icon_size = 32,
        subgroup = "factorican-iron",
        default_temperature = 1000,
        heat_capacity = "0.1KJ",
        -- base_color = {r = 0.75, g = 0.65, b = 0.1},
        -- flow_color = {r = 0.75, g = 0.65, b = 0.1},
        max_temperature = 1000,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
    {
        type = "item",
        name = "fs-reduced-iron-ore",
        icon = "__factoricanindustry__/graphics/icons/items/fs-reduced-iron-ore.png",
        icon_size = 32,
        flags = {"goes-to-main-inventory"},
        subgroup = "factorican-iron",
        order = "z",
        stack_size = 100
    },
    {
        type = "item",
        name = "fs-flux-rock",
        icon = "__factoricanindustry__/graphics/icons/items/fs-flux-rock.png",
        icon_size = 32,
        flags = {"goes-to-main-inventory"},
        subgroup = "factorican-iron",
        order = "z",
        stack_size = 100
    },
    {
        type = "item",
        name = "fs-slag",
        icon = "__factoricanindustry__/graphics/icons/items/fs-slag.png",
        icon_size = 32,
        flags = {"goes-to-main-inventory"},
        subgroup = "factorican-iron",
        order = "z",
        stack_size = 100
    },
    {
        type = "fluid",
        name = "fs-molten-iron",
        icon = "__factoricanindustry__/graphics/icons/items/fs-molten-iron.png",
        icon_size = 32,
        subgroup = "factorican-iron",
        default_temperature = 1000,
        heat_capacity = "0.1KJ",
        -- base_color = {r = 0.75, g = 0.65, b = 0.1},
        -- flow_color = {r = 0.75, g = 0.65, b = 0.1},
        max_temperature = 1000,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
    {
        type = "fluid",
        name = "fs-molten-steel",
        icon = "__factoricanindustry__/graphics/icons/items/fs-molten-steel.png",
        icon_size = 32,
        subgroup = "factorican-iron",
        default_temperature = 1000,
        heat_capacity = "0.1KJ",
        -- base_color = {r = 0.75, g = 0.65, b = 0.1},
        -- flow_color = {r = 0.75, g = 0.65, b = 0.1},
        max_temperature = 1000,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
    {
        type = "item",
        name = "fs-copper-concentrate",
        icon = "__factoricanindustry__/graphics/icons/items/fs-copper-concentrate.png",
        icon_size = 32,
        flags = {"goes-to-main-inventory"},
        subgroup = "factorican-copper",
        order = "z",
        stack_size = 100
    },
    {
        type = "fluid",
        name = "fs-molten-copper",
        icon = "__factoricanindustry__/graphics/icons/items/fs-molten-copper.png",
        icon_size = 32,
        subgroup = "factorican-copper",
        default_temperature = 1000,
        heat_capacity = "0.1KJ",
        -- base_color = {r = 0.75, g = 0.65, b = 0.1},
        -- flow_color = {r = 0.75, g = 0.65, b = 0.1},
        max_temperature = 1000,
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59,
    },
    {
        type = "item",
        name = "fs-copper-anode",
        icon = "__factoricanindustry__/graphics/icons/items/fs-copper-anode.png",
        icon_size = 32,
        flags = {"goes-to-main-inventory"},
        subgroup = "factorican-copper",
        order = "z",
        stack_size = 100
    },
    {
        type = "item",
        name = "fs-copper-cathode",
        icon = "__factoricanindustry__/graphics/icons/items/fs-copper-cathode.png",
        icon_size = 32,
        flags = {"goes-to-main-inventory"},
        subgroup = "factorican-copper",
        order = "z",
        stack_size = 100
    },
})
