require("prototypes.categories")
-- require("prototypes.technology")
require("prototypes.refining.items")
require("prototypes.refining.recipes")
require("prototypes.smelting.items")
require("prototypes.smelting.recipes")
require("prototypes.entities.combustion-turbine")
-- require("prototypes.hydrocarbonrefinery")
-- require("prototypes.hydrocarbonplant")
require("prototypes.entities.metallurgic-smelter")
